# Generated by Django 4.2.5 on 2023-11-05 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не удалось')], max_length=150, verbose_name='статус попытки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='статус рассылки')),
                ('title', models.TextField(max_length=100, verbose_name='тема письма')),
                ('body', models.TextField(max_length=350, verbose_name='тело письма')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак активности')),
                ('customers', models.ManyToManyField(related_name='mailings', to='customer.customer', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
